import type {StegaCleaned} from '@sanity/client/stega'

/**
 * Strips the `StegaString` brand that Sanity 6 applies to every string in a
 * stega-enabled query result.
 *
 * The brand is applied blanket at the type level — it does not model the runtime
 * filter, which already skips any path segment matching /type/i (see
 * `filterDefault` / `hasTypeLike` in @sanity/client). Discriminator fields such as
 * `media.type` are therefore never stega-encoded at runtime, but TypeScript brands
 * them anyway, which breaks assignment to the types generated by `sanity typegen`.
 *
 * This is a type-level cast only. The runtime value is returned untouched, so stega
 * encoding for visual editing is preserved. Use it where a query result is handed to
 * a component typed against a generated `*QueryResult`.
 */
export function unbrandStega<T>(value: T): StegaCleaned<T> {
  return value as StegaCleaned<T>
}
